import type { Complaint, KPISummary, CategoryBreakdown, DailyTrend, User, Notification } from '@/types';

export const MOCK_CITIZEN: User = {
  uid: 'citizen-001',
  displayName: 'Ramesh Kumar',
  email: 'ramesh@example.com',
  phone: '+91 98765 43210',
  role: 'citizen',
  territory: {
    id: 'area-shaikpet',
    name: 'Shaikpet',
    type: 'area',
    state: 'Telangana',
    district: 'Hyderabad',
    mandal: 'Shaikpet',
  },
  createdAt: '2024-01-15T10:00:00Z',
};

export const MOCK_MANDAL_OFFICER: User = {
  uid: 'mandal-officer-001',
  displayName: 'Shaikpet Admin',
  email: 'shaikpet.admin@gov.in',
  role: 'mandal_officer',
  territory: {
    id: 'mandal-shaikpet',
    name: 'Shaikpet Mandal',
    type: 'mandal',
    state: 'Telangana',
    district: 'Hyderabad',
    mandal: 'Shaikpet',
  },
  createdAt: '2023-06-01T09:00:00Z',
};

export const MOCK_DISTRICT_OFFICER: User = {
  uid: 'district-officer-001',
  displayName: 'Hyderabad District Admin',
  email: 'hyd.district@gov.in',
  role: 'district_officer',
  territory: {
    id: 'district-hyderabad',
    name: 'Hyderabad District',
    type: 'district',
    state: 'Telangana',
    district: 'Hyderabad',
  },
  createdAt: '2023-01-01T09:00:00Z',
};

export const MOCK_STATE_ADMIN: User = {
  uid: 'state-admin-001',
  displayName: 'Rajesh Kumar',
  email: 'rajesh@gov.in',
  role: 'state_admin',
  territory: {
    id: 'state-telangana',
    name: 'Telangana',
    type: 'state',
    state: 'Telangana',
  },
  createdAt: '2022-01-01T09:00:00Z',
};

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'complaint-001',
    referenceId: 'CC-4921',
    title: 'Pothole on Main Street',
    description: 'Large pothole near the junction causing accidents.',
    category: 'roads',
    status: 'pending',
    priority: 'high',
    citizenId: 'citizen-001',
    citizenName: 'Ramesh Kumar',
    location: { lat: 17.4125, lng: 78.4012, address: 'Main Street, Shaikpet' },
    areaId: 'area-shaikpet',
    areaName: 'Shaikpet',
    mandalId: 'mandal-shaikpet',
    mandalName: 'Shaikpet',
    districtId: 'dist-hyderabad',
    districtName: 'Hyderabad',
    stateId: 'state-telangana',
    photoUrls: [],
    videoUrls: [],
    createdAt: '2024-08-24T10:00:00Z',
    updatedAt: '2024-08-25T14:15:00Z',
    escalationLevel: 0,
    updates: [
      {
        id: 'upd-001',
        complaintId: 'complaint-001',
        timestamp: '2024-08-24T10:00:00Z',
        status: 'pending',
        note: 'Complaint submitted by citizen.',
        updatedBy: 'citizen-001',
        updatedByName: 'Ramesh Kumar',
        isPublic: true,
      },
      {
        id: 'upd-002',
        complaintId: 'complaint-001',
        timestamp: '2024-08-25T14:15:00Z',
        status: 'assigned',
        note: 'Assigned to Roads maintenance team.',
        updatedBy: 'mandal-officer-001',
        updatedByName: 'Shaikpet Admin',
        isPublic: true,
      },
    ],
  },
  {
    id: 'complaint-002',
    referenceId: 'CC-5012',
    title: 'Leaking pipe near park',
    description: 'Water pipe leaking for 3 days near Shaikpet park.',
    category: 'water',
    status: 'in_progress',
    priority: 'critical',
    citizenId: 'citizen-001',
    citizenName: 'Ramesh Kumar',
    location: { lat: 17.4185, lng: 78.3970, address: 'Near Dargah Rd, Shaikpet' },
    areaId: 'area-shaikpet',
    areaName: 'Shaikpet',
    mandalId: 'mandal-shaikpet',
    mandalName: 'Shaikpet',
    districtId: 'dist-hyderabad',
    districtName: 'Hyderabad',
    stateId: 'state-telangana',
    photoUrls: [],
    videoUrls: [],
    createdAt: '2024-08-23T08:00:00Z',
    updatedAt: '2024-08-26T09:30:00Z',
    escalationLevel: 0,
    updates: [
      {
        id: 'upd-003',
        complaintId: 'complaint-002',
        timestamp: '2024-08-23T08:00:00Z',
        status: 'pending',
        note: 'Complaint submitted.',
        updatedBy: 'citizen-001',
        updatedByName: 'Ramesh Kumar',
        isPublic: true,
      },
      {
        id: 'upd-004',
        complaintId: 'complaint-002',
        timestamp: '2024-08-24T10:00:00Z',
        status: 'assigned',
        note: 'Assigned to Water supply dept.',
        updatedBy: 'mandal-officer-001',
        updatedByName: 'Shaikpet Admin',
        isPublic: true,
      },
      {
        id: 'upd-005',
        complaintId: 'complaint-002',
        timestamp: '2024-08-26T09:30:00Z',
        status: 'in_progress',
        note: 'Work started. Plumbing team on-site.',
        updatedBy: 'mandal-officer-001',
        updatedByName: 'Shaikpet Admin',
        isPublic: true,
      },
    ],
  },
  {
    id: 'complaint-003',
    referenceId: 'CC-5089',
    title: 'Deep pothole causing traffic jam',
    description: 'Deep pothole at Gachibowli junction causing major traffic delays.',
    category: 'roads',
    status: 'assigned',
    priority: 'high',
    citizenId: 'citizen-002',
    citizenName: 'Priya Sharma',
    location: { lat: 17.4408, lng: 78.3482, address: 'Gachibowli Junction' },
    areaId: 'area-gachibowli',
    areaName: 'Gachibowli',
    mandalId: 'mandal-serilingampally',
    mandalName: 'Serilingampally',
    districtId: 'dist-rangareddy',
    districtName: 'Rangareddy',
    stateId: 'state-telangana',
    photoUrls: [],
    videoUrls: [],
    createdAt: '2024-08-25T11:00:00Z',
    updatedAt: '2024-08-25T15:00:00Z',
    escalationLevel: 0,
    updates: [],
  },
  {
    id: 'complaint-004',
    referenceId: 'CC-5102',
    title: 'Major pipe burst flooding main road',
    description: 'Major water pipe burst causing flooding on the main road.',
    category: 'water',
    status: 'pending',
    priority: 'critical',
    citizenId: 'citizen-003',
    citizenName: 'Anand Rao',
    location: { lat: 17.4481, lng: 78.3681, address: 'Hitech City Rd' },
    areaId: 'area-hitech',
    areaName: 'Hitech City',
    mandalId: 'mandal-serilingampally',
    mandalName: 'Serilingampally',
    districtId: 'dist-rangareddy',
    districtName: 'Rangareddy',
    stateId: 'state-telangana',
    photoUrls: [],
    videoUrls: [],
    createdAt: '2024-08-26T07:00:00Z',
    updatedAt: '2024-08-26T07:00:00Z',
    escalationLevel: 0,
    updates: [],
  },
  {
    id: 'complaint-005',
    referenceId: 'CC-5077',
    title: 'Fallen tree blocking side street',
    description: 'Fallen tree after last night storm blocking side street.',
    category: 'disaster_mgmt',
    status: 'pending',
    priority: 'high',
    citizenId: 'citizen-004',
    citizenName: 'Sunita Devi',
    location: { lat: 17.4551, lng: 78.3598, address: 'Madhapur' },
    areaId: 'area-madhapur',
    areaName: 'Madhapur',
    mandalId: 'mandal-serilingampally',
    mandalName: 'Serilingampally',
    districtId: 'dist-rangareddy',
    districtName: 'Rangareddy',
    stateId: 'state-telangana',
    photoUrls: [],
    videoUrls: [],
    createdAt: '2024-08-26T06:00:00Z',
    updatedAt: '2024-08-26T06:00:00Z',
    escalationLevel: 0,
    updates: [],
  },
];

export const MOCK_MANDAL_KPI: KPISummary = {
  total: 124,
  pending: 12,
  assigned: 45,
  inProgress: 30,
  resolved: 32,
  escalated: 5,
  rejected: 0,
  closed: 0,
};

export const MOCK_DISTRICT_KPI: KPISummary = {
  total: 843,
  pending: 78,
  assigned: 312,
  inProgress: 198,
  resolved: 221,
  escalated: 34,
  rejected: 0,
  closed: 0,
};

export const MOCK_STATE_KPI: KPISummary = {
  total: 1200000,
  pending: 45000,
  assigned: 380000,
  inProgress: 290000,
  resolved: 462000,
  escalated: 23000,
  rejected: 0,
  closed: 0,
};

export const MOCK_CATEGORY_BREAKDOWN: CategoryBreakdown[] = [
  { category: 'roads', count: 50, percentage: 40 },
  { category: 'water', count: 31, percentage: 25 },
  { category: 'drainage', count: 19, percentage: 15 },
  { category: 'sanitation', count: 14, percentage: 11 },
  { category: 'other', count: 10, percentage: 9 },
];

export const MOCK_WEEKLY_TREND: DailyTrend[] = [
  { date: 'Mon', count: 18 },
  { date: 'Tue', count: 22 },
  { date: 'Wed', count: 15 },
  { date: 'Thu', count: 28 },
  { date: 'Fri', count: 20 },
  { date: 'Sat', count: 12 },
  { date: 'Sun', count: 10 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'citizen-001',
    type: 'complaint_status_update',
    title: 'Work Started on #CC-5012',
    body: 'The plumbing team has started work on your leaking pipe complaint.',
    complaintId: 'complaint-002',
    complaintRef: 'CC-5012',
    isRead: false,
    createdAt: '2024-08-26T09:30:00Z',
  },
  {
    id: 'notif-002',
    userId: 'citizen-001',
    type: 'complaint_assigned',
    title: 'Complaint Assigned: #CC-4921',
    body: 'Your pothole complaint has been assigned to the Roads team.',
    complaintId: 'complaint-001',
    complaintRef: 'CC-4921',
    isRead: true,
    createdAt: '2024-08-25T14:15:00Z',
  },
];

export const MOCK_DISTRICT_ROWS = [
  { id: 'dist-1', name: 'Kondapur', total: 124, pending: 12, resolved: 32, escalated: 5, sla: 87 },
  { id: 'dist-2', name: 'Gachibowli', total: 98, pending: 8, resolved: 61, escalated: 2, sla: 92 },
  { id: 'dist-3', name: 'Madhapur', total: 76, pending: 15, resolved: 43, escalated: 7, sla: 78 },
  { id: 'dist-4', name: 'Jubilee Hills', total: 112, pending: 20, resolved: 67, escalated: 4, sla: 83 },
  { id: 'dist-5', name: 'Banjara Hills', total: 89, pending: 9, resolved: 55, escalated: 3, sla: 90 },
];

export const MOCK_STATE_DISTRICTS = [
  { id: 'sd-1', name: 'Hyderabad', total: 420000, resolution: 76.2, escalated: 8200, trend: '+2.1%' },
  { id: 'sd-2', name: 'Rangareddy', total: 186000, resolution: 81.4, escalated: 3400, trend: '+0.8%' },
  { id: 'sd-3', name: 'Medchal', total: 142000, resolution: 69.7, escalated: 5100, trend: '+3.2%' },
  { id: 'sd-4', name: 'Sangareddy', total: 98000, resolution: 84.1, escalated: 1900, trend: '-0.3%' },
  { id: 'sd-5', name: 'Warangal', total: 112000, resolution: 78.9, escalated: 2800, trend: '+1.5%' },
];
