import type { Complaint } from '@/types';
import { MOCK_COMPLAINTS } from './mockData';

export const INITIAL_COMPLAINTS: Complaint[] = [
  ...MOCK_COMPLAINTS,
  {
    id: 'complaint-006',
    referenceId: 'CC-8821',
    title: 'Severe waterlogging near Community Hall',
    description: 'After yesterday heavy downpour, the drainage overflowed and water is stagnating up to 2 feet near the main community hall entrance.',
    category: 'drainage',
    status: 'in_progress',
    priority: 'high',
    citizenId: 'user-citizen-01',
    citizenName: 'Ramesh Kumar',
    location: {
      lat: 17.4485,
      lng: 78.3752,
      address: 'Plot 42, Hitech City Main Rd, Madhapur',
    },
    areaId: 'area-madhapur',
    areaName: 'Madhapur',
    mandalId: 'mandal-serilingampally',
    mandalName: 'Serilingampally',
    districtId: 'dist-rangareddy',
    districtName: 'Rangareddy',
    stateId: 'state-telangana',
    photoUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb180c5f5?w=600&auto=format&fit=crop&q=60'],
    videoUrls: [],
    assignedTo: 'user-mandal-01',
    assignedToName: 'Suresh Verma (Field Supervisor)',
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    escalationLevel: 0,
    updates: [
      {
        id: 'u-1',
        complaintId: 'complaint-006',
        timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
        status: 'pending',
        note: 'Complaint registered by citizen via mobile app.',
        updatedBy: 'user-citizen-01',
        updatedByName: 'Ramesh Kumar',
        isPublic: true,
      },
      {
        id: 'u-2',
        complaintId: 'complaint-006',
        timestamp: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
        status: 'assigned',
        note: 'Assigned to Serilingampally Drainage Quick Response Team.',
        updatedBy: 'user-mandal-01',
        updatedByName: 'Suresh Verma',
        isPublic: true,
      },
      {
        id: 'u-3',
        complaintId: 'complaint-006',
        timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        status: 'in_progress',
        note: 'Suction pump machinery deployed on site. De-silting in progress.',
        updatedBy: 'user-mandal-01',
        updatedByName: 'Suresh Verma',
        isPublic: true,
      },
    ],
  },
  {
    id: 'complaint-007',
    referenceId: 'CC-9140',
    title: 'Faulty high-voltage street transformer sparking',
    description: 'Electric transformer sparking intermittently near Primary School. Poses severe electrocution risk to children.',
    category: 'electricity',
    status: 'escalated',
    priority: 'critical',
    citizenId: 'user-citizen-02',
    citizenName: 'Anita Sharma',
    location: {
      lat: 17.4325,
      lng: 78.4072,
      address: 'Opposite Govt School, Road No 10, Jubilee Hills',
    },
    areaId: 'area-jubilee-hills',
    areaName: 'Jubilee Hills',
    mandalId: 'mandal-shaikpet',
    mandalName: 'Shaikpet',
    districtId: 'dist-hyderabad',
    districtName: 'Hyderabad',
    stateId: 'state-telangana',
    photoUrls: ['https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=600&auto=format&fit=crop&q=60'],
    videoUrls: [],
    assignedTo: 'user-district-01',
    assignedToName: 'District Electrical Inspector',
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    escalationLevel: 1,
    escalatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updates: [
      {
        id: 'u-1',
        complaintId: 'complaint-007',
        timestamp: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        status: 'pending',
        note: 'Urgent complaint submitted.',
        updatedBy: 'user-citizen-02',
        updatedByName: 'Anita Sharma',
        isPublic: true,
      },
      {
        id: 'u-2',
        complaintId: 'complaint-007',
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        status: 'escalated',
        note: 'SLA breached (24h Critical). Auto-escalated to District Officer.',
        updatedBy: 'system',
        updatedByName: 'SLA Escalation Engine',
        isPublic: true,
      },
    ],
  },
  {
    id: 'complaint-008',
    referenceId: 'CC-3320',
    title: 'Potholes repaired on Gandhi Road',
    description: 'Road resurfacing and patch work completed.',
    category: 'roads',
    status: 'resolved',
    priority: 'medium',
    citizenId: 'user-citizen-01',
    citizenName: 'Ramesh Kumar',
    location: {
      lat: 17.4532,
      lng: 78.3685,
      address: 'Gandhi Rd, KPHB Colony, Kukatpally',
    },
    areaId: 'area-kukatpally',
    areaName: 'Kukatpally',
    mandalId: 'mandal-kukatpally',
    mandalName: 'Kukatpally',
    districtId: 'dist-medchal',
    districtName: 'Medchal-Malkajgiri',
    stateId: 'state-telangana',
    photoUrls: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=60'],
    videoUrls: [],
    assignedTo: 'user-mandal-02',
    assignedToName: 'K. Rao (Junior Engineer)',
    createdAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    escalationLevel: 0,
    citizenRating: 5,
    citizenFeedback: 'Very prompt action by the engineering team! Thank you.',
    updates: [
      {
        id: 'u-1',
        complaintId: 'complaint-008',
        timestamp: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
        status: 'pending',
        note: 'Submitted.',
        updatedBy: 'user-citizen-01',
        updatedByName: 'Ramesh Kumar',
        isPublic: true,
      },
      {
        id: 'u-2',
        complaintId: 'complaint-008',
        timestamp: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        status: 'resolved',
        note: 'Bitumen patch repair completed and tested.',
        updatedBy: 'user-mandal-02',
        updatedByName: 'K. Rao',
        isPublic: true,
      },
    ],
  },
];
